title:            Welcome to my  Blog
description:      "敬畏耶和华是智慧的开端 (111:10)"
logo:             omikron.png
disqus_shortname:
duoshuo_shortname:  i2brother
# Assign a default image for your site's header and footer
default_bg:       http://froyobin.github.io/home/images/my_bg.png
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      200
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:       		   http://froyobin.github.io/home

# Owner/author information
owner:
  name:           froyobin
  avatar:         moe.png
  email:          frobin.bin@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    animal
  # Social networking links used in footer. Update and remove as you like.
  twitter:        froyobin
  facebook:       froyobin.me
  github:
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  weibo: 
  # For Google Authorship https://plus.google.com/authorship
google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-52116871-3
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
    icon: bars
  - title: Tags
    url: /tags
    icon: tags
  - title: Guestbook
    url: /guestbook
    icon: comments
  - title: Links
    url: /links
    icon: link
  - title: About
    url: /about
    icon: user

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown
excerpt_separator: "<!--more-->"
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
